# Copyright (c) 02.10.2023 Thomas Zierer.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#    Thomas Zierer - initial API and implementation and/or initial documentation

name: Java CI with Maven

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
      # Skip java code signing. Activate it if you have a certificate
      # Use system JDK. If you're still on java 8 use "BREE" and add a java 17 to your toolchain
      # Skip test (only work on Windows) 
    - name: Build with Maven
      run: mvn -B verify -Djcs.skip=true -Dtycho-useJDK=SYSTEM -DskipTests=true --file de.tgmz.zdev/pom.xml
